# Generated by Django 4.2 on 2025-11-25 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='射程')),
                ('comment', models.TextField(blank=True, verbose_name='空')),
                ('comment2', models.TextField(blank=True, verbose_name='空')),
                ('image1', models.ImageField(null=True, upload_to='photos', verbose_name='武器の写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='武器の名前')),
            ],
        ),
    ]
